# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 17:26
# This is an edited file though!
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Group')),
            ],
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Member')),
            ],
            bases=(models.Model,),
        ),
    ]
